name: clima
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <9.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  geolocator:
  geocoding:
  http:
  intl:
  flutter_dotenv:


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
  - .env

  fonts:
  - family: Spartan MB
    fonts:
    - asset: fonts/SpartanMB-Black.otf
      weight: 900